package com.sample
import com.sample.AfterWorkDrink;

 
declare Pytanie
   pytanie : String
   odpowiedzi : Object[]
   udzielona_odpowiedz : String
end
declare Odpowiedz
	odpowiedz : String
	opis : String
	ikona : String
end

rule "Start"
	when
	then
		Pytanie p = new Pytanie("Who are you going out for drinks with?", new Object[]{"Your boss","A colleague", "A group", "A client or business contact"},"");

		String answer = AfterWorkDrink.AskQuestion(p.getPytanie(), p.getOdpowiedzi());
		p.setUdzielona_odpowiedz(answer);
		insert(p);
end

rule "Is it an official functon?"
	when
		p: Pytanie(pytanie == "Who are you going out for drinks with?", udzielona_odpowiedz == "A group")
	then
		Pytanie p2 = new Pytanie("Is it an official functon?", new Object[]{"Yes","No"},"");
		String answer = AfterWorkDrink.AskQuestion(p2.getPytanie(), p2.getOdpowiedzi());
		p2.setUdzielona_odpowiedz(answer);
		insert(p2);
end

rule "Do you like these people?"
	when
		p: Pytanie(pytanie == "Is it an official functon?", udzielona_odpowiedz == "No")
	then
		Pytanie p2 = new Pytanie("Do you like these people?", new Object[]{"No","Eh"},"");
		String answer = AfterWorkDrink.AskQuestion(p2.getPytanie(), p2.getOdpowiedzi());
		p2.setUdzielona_odpowiedz(answer);
		insert(p2);
end

rule "5.Fancy cocktail"
	when
		p: Pytanie(pytanie == "Do you like these people?", udzielona_odpowiedz == "No")
	then
		Odpowiedz o = new Odpowiedz("Fancy cocktail", "Cudowna odpowiedz", "icons/fancy.png");
		insert(o);
		AfterWorkDrink.ShowAnswer(o.getOdpowiedz(), o.getOpis(), o.getIkona());
end
